#!/usr/bin/env python3
"""
Calculates and plots the blue-tilted stochastic gravitational wave background (SGWB)
spectral energy density Omega_GW(f) generated by a transient hyper-stiff brane rupture phase.
"""

import os
import numpy as np
import matplotlib.pyplot as plt


def calculate_gw_spectrum():
    """
    Compute the SGWB spectral energy density Omega_GW(f) produced by
    a transient hyper-stiff (w >> 1) brane-rupture phase.

    The spectrum is:
      - anchored at PTA frequencies with Omega_PTA at f_anchor,
      - blue-tilted with n_T set by the hyper-stiff equation of state,
      - exponentially suppressed above a cutoff frequency set by the
        finite duration of the rupture phase.
    """
    # 1. Define frequency range (Hz) spanning from PTA bands to space-based interferometers
    frequencies = np.logspace(-11, -1, 1000)

    # 2. Model parameters linked to the hubble-tension-geometry core baseline
    w_peak = 80.0
    n_T = (6.0 * w_peak - 2.0) / (1.0 + 3.0 * w_peak)  # Dynamically yields n_T ≈ +2.0

    # Reference anchor frequency (Hz) at the NANOGrav/PTA target node
    f_anchor = 1e-9
    Omega_PTA = 1e-14  # Typical amplitude measured by pulsar timing arrays

    # 3. Calculate power-law amplification spectrum
    omega_pure = Omega_PTA * (frequencies / f_anchor) ** n_T

    # 4. Implement high-frequency cut-off envelope dictated by the phase width Delta_a
    #    f_cutoff corresponds to the end of the hyper-stiff rupture phase; modes above
    #    this scale are exponentially suppressed because they never see the full spike.
    f_cutoff = 1e-3
    attenuation = np.exp(-(frequencies / f_cutoff) ** 2)
    omega_gw = omega_pure * attenuation

    return frequencies, omega_gw


def plot_and_save():
    # Set professional journal plotting parameters
    plt.rcParams["text.usetex"] = False  # Set to True if local LaTeX compiler is available
    plt.rcParams["font.family"] = "serif"
    plt.rcParams["font.size"] = 11
    plt.rcParams["axes.linewidth"] = 1.0

    f, omega = calculate_gw_spectrum()

    fig, ax = plt.subplots(figsize=(7, 4.5))

    # Plot primary theoretical signature curve
    ax.loglog(
        f,
        omega,
        color="#003366",
        linewidth=2.2,
        label=r"Brane Rupture Model ($w_{\max} \approx 80$)",
    )

    # Overlay observational target windows for visual reference
    # PTA / NANOGrav band (Nano-Hertz)
    ax.axvspan(1e-9, 1e-7, color="#ff9999", alpha=0.25, label="PTA Observation Band")
    # LISA / DECIGO target band (Milli-Hertz)
    ax.axvspan(
        1e-4,
        1e-1,
        color="#99ccff",
        alpha=0.25,
        label="LISA / DECIGO Sensitivity Window",
    )

    # Plot formatting
    ax.set_xlabel(r"Frequency $f$ [Hz]", labelpad=8)
    ax.set_ylabel(r"Spectral Density $\Omega_{\mathrm{GW}}(f)$", labelpad=8)
    ax.set_xlim(1e-11, 1e-1)
    ax.set_ylim(1e-16, 1e-5)
    ax.grid(True, which="both", linestyle=":", alpha=0.4, color="#888888")

    # Position text labels inside the active panels for visual anchors
    ax.text(
        2e-10,
        5e-13,
        r"$n_T \simeq +2.0$",
        fontsize=12,
        color="#003366",
        fontweight="bold",
    )

    ax.legend(
        loc="upper left",
        frameon=True,
        facecolor="white",
        edgecolor="#dddddd",
        framealpha=0.9,
    )
    plt.tight_layout()

    # Ensure output directory exists
    os.makedirs("figures", exist_ok=True)
    output_pdf = os.path.join("figures", "figure_gw.pdf")
    output_png = os.path.join("figures", "figure_gw.png")

    # Save clean dual outputs for GitHub and LaTeX builds
    plt.savefig(output_pdf, bbox_inches="tight", dpi=300)
    plt.savefig(output_png, bbox_inches="tight", dpi=300)
    plt.close()

    print(f"[SUCCESS] Saved vector plot: {output_pdf}")
    print(f"[SUCCESS] Saved web preview: {output_png}")

    return fig, ax


if __name__ == "__main__":
    plot_and_save()
